#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from oregon_trail
import oregon_trail
from oregon_trail.lib import try_me

if __name__ == '__main__':
    try_me()
